# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTNetwork',
    'RCTWebSocket',
    'DevSupport'
  ]
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

end
